### PR TITLE
Lrqa 76039

### PR DESCRIPTION
**Pull request by weller0246**

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:stop

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by weller0246** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
Continued in https://github.com/gaborlovasdotcom/liferay-portal/pull/418

**Review by gaborlovasdotcom — COMMENTED** [review]
This PR has been updated and forwarded to BChan:
https://github.com/brianchandotcom/liferay-portal/pull/121380

**Pull request closed without merging**
