### PR TITLE
LPS-147522 | master

### PR DESCRIPTION
**Pull request by weller0246**
[LPS-147522](https://issues.liferay.com/browse/LPS-147522)

### CODE REVIEW

**Comment by weller0246** [comment]
ci:test:sf

**Comment by weller0246** [comment]
ci:test:staging

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
ci:test:staging:nocompile

**Comment by weller0246** [comment]
@gaborlovasdotcom  @JoyceWang08211  please review my new test if you have the time!

**Comment by weller0246** [comment]
ci:test:sf

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, please remove the CI only part and change the ID in the description and it's good to go

**Review by gaborlovasdotcom — CHANGES_REQUESTED** [review]

**Comment by JoyceWang08211** [comment]
LGTM

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
